package com.labresa.model;

import java.time.LocalDateTime;

/** A single notification delivered to a user, generated by the Observer pattern. */
public class Notification {

    public enum Type { APPROVAL_RESULT, MAINTENANCE_ALERT, SLOT_FREED, PENDING_APPROVAL }

    private int id;
    private final int userId;
    private final Integer reservationId; // nullable
    private final String message;
    private final Type type;
    private boolean read;
    private final LocalDateTime createdAt;

    public Notification(int id, int userId, Integer reservationId, String message,
                         Type type, boolean read, LocalDateTime createdAt) {
        this.id = id;
        this.userId = userId;
        this.reservationId = reservationId;
        this.message = message;
        this.type = type;
        this.read = read;
        this.createdAt = createdAt;
    }

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }
    public int getUserId() { return userId; }
    public Integer getReservationId() { return reservationId; }
    public String getMessage() { return message; }
    public Type getType() { return type; }
    public boolean isRead() { return read; }
    public void setRead(boolean read) { this.read = read; }
    public LocalDateTime getCreatedAt() { return createdAt; }
}